# Generated by Django 5.2.3 on 2025-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(null=True)),
                ('wickets', models.IntegerField(null=True)),
                ('balls', models.IntegerField(null=True)),
                ('wideBalls', models.IntegerField(null=True)),
                ('batsman', models.CharField(max_length=70)),
                ('bawler', models.CharField(max_length=70)),
                ('battingTeam', models.CharField(max_length=70)),
                ('bawlingteam', models.CharField(max_length=70)),
            ],
        ),
    ]
