# Generated by Django 5.2.3 on 2025-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='wideBalls',
            new_name='wideballs',
        ),
        migrations.AddField(
            model_name='match',
            name='ismatchover',
            field=models.BooleanField(default=False),
        ),
    ]
