# Generated by Django 5.2.3 on 2025-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_wideballs_match_wideballs_match_ismatchover'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='innings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='isinningsover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team1runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team1wickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
