# Generated by Django 5.2.3 on 2025-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_match_innings_match_isinningsover_match_team1runs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='battingTeam',
            new_name='battingteam',
        ),
        migrations.AlterField(
            model_name='match',
            name='team1runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1wickets',
            field=models.IntegerField(default=0),
        ),
    ]
