# Generated by Django 5.2.3 on 2025-06-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_battingteam_match_battingteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='isinningsover',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ismatchover',
        ),
    ]
